### ISSUE TITLE
On READY event return null for ClientUser property

### ISSUE THREAD

**Issue by Polaris1999** [OwenCalvin/DiscordTS#2]
### **Problem:**
![on_ready_user_null](https://user-images.githubusercontent.com/36986784/70848629-1f328e00-1ea7-11ea-89d6-d6cb33fe8726.png)
![image](https://user-images.githubusercontent.com/36986784/70846985-b12f9c00-1e91-11ea-8490-6a7ea8dad361.png)
When i try to use the  "ready" event, the value for user (UserClient) is null and i cannot use any of the ClientUser instance or method.
### **Expectation:**
We should be able to use it the way the native discord.js module do
`
bot.on('ready', () => { bot.user.setActivity(...) })
`
### **My workaround solution for now:**
![workaround_solution](https://user-images.githubusercontent.com/36986784/70848658-77699000-1ea7-11ea-9561-29a14bfda51a.png)

Much appreciate if you can fix it in the near feature :)

**Comment by Fredi100** [comment]
Isn't `onReady` in your case a member of the class you decorated with `@Discord`.
Your own class does not inherit Client. If you wan't access to the properties of the discord client object, you need to use it this way:
```Typescript
@On('ready')
async onReady(client: Client){
    console.log(client.user);
    // Do stuff with user
}
```

**Comment by TheDevMinerTV** [comment]
![image](https://user-images.githubusercontent.com/29845135/76640473-48b79000-6550-11ea-8f6e-252c5e07f4ab.png)
Okay, so I have the same issue and for some reason `@On('ready')` gets called twice.

**Comment by Polaris1999** [comment]
> Isn't `onReady` in your case a member of the class you decorated with `@Discord`.
> Your own class does not inherit Client. If you want access to the properties of the discord client object, you need to use it this way:
> 
> ```ts
> @On('ready')
> async onReady(client: Client){
>     console.log(client.user);
>     // Do stuff with user
> }
> ```

The function is inside a class decorated with @Discord, do i still need to pass in the parameter for Client ?

**Comment by Fredi100** [comment]
Yes. `@On` injects the client object as the last parameter of the function which is why you have to include it. Take a quick look at the [Readme](https://github.com/OwenCalvin/DiscordTS#client-payload-injection)

**Comment by OwenCalvin** [comment]
Yes you have to use the client parameter on the event function :)

Thank's @Fredi100 for the support!
