### ISSUE TITLE
Customize @On Decorator

### ISSUE THREAD

**Issue by Fredi100** [OwenCalvin/DiscordTS#3]
Adding the ability to further narrow down the On decorator.
Example:
```TS
@On('message','begins','!Foo') // Message begins with !Foo
private onCommandFoo(message: Message){
    // ...
}

@On('message','equals','!help') // Message equals !help
private onCommandHelp(message: Message){
    // ...
}

@On('message','contains','#bar') // Message contains #bar
private onHashtagBar(message: Message){
    // ...
}
```

This way instead of having one `onMessage` method which has to handle all commands that a user could send, there could be multiple methods for different commands.

**Comment by OwenCalvin** [comment]
Very interesting feature ! Thank’s I’m going to work on it :)

**Comment by Fredi100** [comment]
I have made a pull request regarding this feature. Maybe you can link the request to this issue.

**Comment by OwenCalvin** [comment]
I implemented the @Guard (and the Prefix function) decorator !
The documentation is here! :)
